<?php

/**
 * @file
 * Contains civicrm_entity_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function civicrm_entity_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the civicrm_entity_access module.
    case 'help.page.civicrm_entity_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Control access to CiviCRM entities through standard Drupal entity management.') . '</p>';
      return $output;

    default:
  }
}
